// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureStatus() {
  return window['go']['main']['App']['CaptureStatus']();
}

export function NotifyUpdateAvailable(arg1) {
  return window['go']['main']['App']['NotifyUpdateAvailable'](arg1);
}

export function StartCapture(arg1) {
  return window['go']['main']['App']['StartCapture'](arg1);
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}
