// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureStatus():Promise<string>;

export function GetUserEmail():Promise<string>;

export function IsLoggedIn():Promise<boolean>;

export function Login():Promise<void>;

export function Logout():Promise<void>;

export function NotifyUpdateAvailable(arg1:string):Promise<void>;

export function StartCapture(arg1:string):Promise<void>;

export function StopCapture():Promise<void>;
